# Generated by Django 3.2.13 on 2022-04-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0037_erratum_erratumevent'),
    ]

    # Due to https://code.djangoproject.com/ticket/23740 we must use a manual
    # migration in order to delete the incorrect single-field unique_together
    # on osidb_flaw...
    # https://stackoverflow.com/a/12396684
    operations = [
        migrations.RunSQL(
            """
            -- We need the DO command in order to fetch the correct unique
            -- constraint name, as the ALTER TABLE command does not support
            -- subqueries.
            DO
            $body$
            DECLARE
                _con text := (
                    SELECT quote_ident(conname)
                    FROM pg_constraint
                    WHERE conrelid = 'osidb_flaw'::regclass
                    AND contype = 'u'
                    -- Recent Django versions have two schemes for constraint
                    -- names unlike what the Trac bug ticket mentions. For
                    -- unique=True the scheme is <table_name>_<field_name>_key
                    -- and for unique_together constraints it's
                    -- <table_name>_<field_names>_<hash>_uniq, that is why we
                    -- explicitly check for the latter using LIKE as we cannot
                    -- guess the hash and it will be different in each env.
                    AND conname LIKE 'osidb_flaw_cve_id_%_uniq'
                );
            BEGIN
                EXECUTE
                    'ALTER TABLE osidb_flaw DROP CONSTRAINT ' || _con;
            END
            $body$;
            """
        ),
        # does nothing but if not applied Django will auto-generate it
        migrations.AlterUniqueTogether(
            name='flaw',
            unique_together=set(),
        ),
    ]
